### ISSUE TITLE
Unsatisfiable ZP:0100801 (Fix ZFIN)

### ISSUE THREAD

**Issue by matentzn** [obophenotype/zebrafish-phenotype-ontology#11]
Logical definition:

```
'has part' some 
('increased occurrence' and ('inheres in' some 
('protein kinase activity' and ('part of' some 'cardiac ventricle'))) 
and ('has modifier' some abnormal))
```
**Problem**: kinase activity is a process, cardiac ventrical a material entity. part_of is the wrong relation.
**Solution**: ZFIN record should use 'occurs_in' in column `Post-composed Relationship ID` instead of 'part_of'.

Refer to [this table](https://github.com/obophenotype/zebrafish-phenotype-ontology/blob/master/src/curation/zp_zfin_phenotype_fish.tsv) to find the broken record.

**Comment by ybradford** [comment]
@matentzn this seems to be referenced in #13 . I'm just going to close this because fixing #13  will fix this as well.
