### ISSUE TITLE
Unsatisfiable ZP:0103876 (Fix ZFIN)

### ISSUE THREAD

**Issue by matentzn** [obophenotype/zebrafish-phenotype-ontology#12]
Logical definition:

```
'has part' some 
('process quality' and ('inheres in' some 
('glutathione transferase activity' and ('part of' some 'whole organism')))
```

**Problem**: 'glutathione transferase activity' is a process, 'whole organism' a material entity. part_of is the wrong relation.
**Solution**: ZFIN record should use 'occurs_in' in column `Post-composed Relationship ID` instead of 'part_of'. Note that this entry comes from a 'normal' phenotype entry; it should nevertheless be correct.

Refer to [this table](https://github.com/obophenotype/zebrafish-phenotype-ontology/blob/master/src/curation/zp_zfin_phenotype_fish.tsv) to find the broken record.

**Comment by ybradford** [comment]
@matentzn this issue seems to be referenced in #13 . I'm just going to close this because fixing #13 will fix this as well.
