### ISSUE TITLE
Unsatisfiable 'activity in anatomy' Classes (Fix ZFIN)

### ISSUE THREAD

**Issue by matentzn** [obophenotype/zebrafish-phenotype-ontology#13]
It appears that all the following classes follow the same problem: a kind of activity occurs in an anatomy, but ZFIN uses 'part_of' instead of 'occurs_in' to model this. So I guess our unsatisfiable problem is smaller than I thought.

Phenotypes with activities that occur in an anatomical structure:
* http://purl.obolibrary.org/obo/ZP_0100801
* http://purl.obolibrary.org/obo/ZP_0103876
* http://purl.obolibrary.org/obo/ZP_0103875
* http://purl.obolibrary.org/obo/ZP_0103035
* http://purl.obolibrary.org/obo/ZP_0103510
* http://purl.obolibrary.org/obo/ZP_0003464
* http://purl.obolibrary.org/obo/ZP_0016275
* http://purl.obolibrary.org/obo/ZP_0022622
* http://purl.obolibrary.org/obo/ZP_0022623
* http://purl.obolibrary.org/obo/ZP_0020405
* http://purl.obolibrary.org/obo/ZP_0022547
* http://purl.obolibrary.org/obo/ZP_0103509
* http://purl.obolibrary.org/obo/ZP_0003461
* http://purl.obolibrary.org/obo/ZP_0101246
* http://purl.obolibrary.org/obo/ZP_0021590
* http://purl.obolibrary.org/obo/ZP_0101044
* http://purl.obolibrary.org/obo/ZP_0101165
* http://purl.obolibrary.org/obo/ZP_0100311
* http://purl.obolibrary.org/obo/ZP_0101047
* http://purl.obolibrary.org/obo/ZP_0101245
* http://purl.obolibrary.org/obo/ZP_0103032
* http://purl.obolibrary.org/obo/ZP_0103031
* http://purl.obolibrary.org/obo/ZP_0103034
* http://purl.obolibrary.org/obo/ZP_0103033
* http://purl.obolibrary.org/obo/ZP_0016882
* http://purl.obolibrary.org/obo/ZP_0017531
* http://purl.obolibrary.org/obo/ZP_0003452
* http://purl.obolibrary.org/obo/ZP_0003453
* http://purl.obolibrary.org/obo/ZP_0003455
* http://purl.obolibrary.org/obo/ZP_0003456
* http://purl.obolibrary.org/obo/ZP_0022559
* http://purl.obolibrary.org/obo/ZP_0012644
* http://purl.obolibrary.org/obo/ZP_0017619
* http://purl.obolibrary.org/obo/ZP_0015312
* http://purl.obolibrary.org/obo/ZP_0011353
* http://purl.obolibrary.org/obo/ZP_0012000
* http://purl.obolibrary.org/obo/ZP_0101037
* http://purl.obolibrary.org/obo/ZP_0101313
* http://purl.obolibrary.org/obo/ZP_0013539
* http://purl.obolibrary.org/obo/ZP_0016921
* http://purl.obolibrary.org/obo/ZP_0012645
* http://purl.obolibrary.org/obo/ZP_0016922
* http://purl.obolibrary.org/obo/ZP_0101431
* http://purl.obolibrary.org/obo/ZP_0102488
* http://purl.obolibrary.org/obo/ZP_0101162
* http://purl.obolibrary.org/obo/ZP_0101042
* http://purl.obolibrary.org/obo/ZP_0101163
* http://purl.obolibrary.org/obo/ZP_0101043
* http://purl.obolibrary.org/obo/ZP_0101164
* http://purl.obolibrary.org/obo/ZP_0019489
* http://purl.obolibrary.org/obo/ZP_0013461
* http://purl.obolibrary.org/obo/ZP_0023018
* http://purl.obolibrary.org/obo/ZP_0019481
* http://purl.obolibrary.org/obo/ZP_0102917
* http://purl.obolibrary.org/obo/ZP_0014675
* http://purl.obolibrary.org/obo/ZP_0100579
* http://purl.obolibrary.org/obo/ZP_0013462
* http://purl.obolibrary.org/obo/ZP_0014750
* http://purl.obolibrary.org/obo/ZP_0100813
* http://purl.obolibrary.org/obo/ZP_0101224
* http://purl.obolibrary.org/obo/ZP_0018875
* http://purl.obolibrary.org/obo/ZP_0018878
* http://purl.obolibrary.org/obo/ZP_0012579
* http://purl.obolibrary.org/obo/ZP_0101222
* http://purl.obolibrary.org/obo/ZP_0101223
* http://purl.obolibrary.org/obo/ZP_0014080
* http://purl.obolibrary.org/obo/ZP_0019494
* http://purl.obolibrary.org/obo/ZP_0102483
* http://purl.obolibrary.org/obo/ZP_0019497
* http://purl.obolibrary.org/obo/ZP_0012581
* http://purl.obolibrary.org/obo/ZP_0009937
* http://purl.obolibrary.org/obo/ZP_0021724

Laminase binding
* http://purl.obolibrary.org/obo/ZP_0008731

Example:
```
'has part' some 
('increased occurrence' and ('inheres in' some 
('protein kinase activity' and ('part of' some 'cardiac ventricle'))) 
and ('has modifier' some abnormal))
```
**Problem**: 'protein kinase activity' is a process, cardiac ventrical a material entity. part_of is the wrong relation.
**Solution**: ZFIN record should use 'occurs_in' in column `Post-composed Relationship ID` instead of 'part_of'.

Refer to [this table](https://github.com/obophenotype/zebrafish-phenotype-ontology/blob/master/src/curation/zp_zfin_phenotype_fish.tsv) to find the broken record.

If the record is not found in the above table, it means that the culprit lies in one of the intermediate classes we have already added; just post here which ones and I will fix them.

**Comment by matentzn** [comment]
For the interested (can be ignored, just for documentation): the following axioms occur in virtually all explanations:

Axioms that cause activities to be occurrents:
* 'process' SubClassOf 'occurrent' (100)
* 'molecular_function' SubClassOf 'process' (97)
* 'catalytic activity' SubClassOf 'molecular_function' (74)

A number of axioms (not necessarily occurring together) that ensures the anatomical structures to turn out as continuants:
* 'relation between structure and stage' Domain 'continuant' (94)
* 'existence starts during or after' SubPropertyOf: 'relation between structure and stage' (91)
* 'part of' o 'develops_from' SubPropertyOf: 'develops_from' (90)
* 'develops_from' SubPropertyOf: 'developmentally preceded by' (84)
* 'developmentally preceded by' o 'existence starts during or after' SubPropertyOf: 'existence starts during or after' (83)

The famous axioms causing the break:
* 'continuant' DisjointWith 'occurrent' (94)
* 'continuant' DisjointWith 'part of' some 'occurrent' (4)
* 'occurrent' DisjointWith 'part of' some 'continuant' (3)

**Comment by ybradford** [comment]
I can work on these

**Comment by matentzn** [comment]
See email, but see 

- [here](https://github.com/obophenotype/zebrafish-phenotype-ontology/blob/master/src/curation/unsat.txt_zp_zfin_phenotype_fish.tsv) for all 107 relevant fish annotations 
- [here](https://github.com/obophenotype/zebrafish-phenotype-ontology/blob/master/src/curation/unsat.txt_zp_zfin_phenoGeneCleanData_fish.tsv) for all 49 relevant gene annotations

**Comment by matentzn** [comment]
Thanks @ybradford these appear fixed.
