### ISSUE TITLE
NTR yolk edema

### ISSUE THREAD

**Issue by diatomsRcool** [obophenotype/zebrafish-phenotype-ontology#17]
For new term requests, please provide the following information:

## Preferred term label

yolk edema

## Textual definition

combination of yolk in UBERON and edetamous in PATO

## Suggested parent term

not sure

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by ybradford** [comment]
yolk can not be edematous. Perhaps you mean yolk syncytial layer ZFA:0000088 http://purl.obolibrary.org/obo/ZFA_0000088.

Note we do not use UBERON in ZP, but rather ZFA terms.

**Comment by ybradford** [comment]
this term already exists in ZFP:  yolk syncytial layer edematous, abnormal

**Comment by diatomsRcool** [comment]
OK, I'll use that.
