### ISSUE TITLE
NTR abnormal tail morphology

### ISSUE THREAD

**Issue by diatomsRcool** [obophenotype/zebrafish-phenotype-ontology#18]
For new term requests, please provide the following information:

## Preferred term label

abnormal tail morphology

## Textual definition

combination of UBERON tail and PATO malformed

## Suggested parent term

not sure

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by ybradford** [comment]
this term should already exist - it would be caudal fin morphology, abnormal. In zebrafish the caudal fin is the 'tail'. Tail is the exact synonym of caudal fin in the ZFA.

**Comment by ybradford** [comment]
this term is also in ZP already, yolk syncytial layer edematous, abnormal

**Comment by diatomsRcool** [comment]
ok I'll use that
