### ISSUE TITLE
ZFIN sometimes uses GO:0005623 (cell) rather than ZFA. Intended?

### ISSUE THREAD

**Issue by matentzn** [obophenotype/zebrafish-phenotype-ontology#30]
Example:
```
ZDB-FISH-150901-29105	WT	ZDB-STAGE-010723-8	Larval:Protruding-mouth	ZDB-STAGE-010723-8	Larval:Protruding-mouth					ZFA:0001315	atrioventricular canal	PATO:0002001	has fewer parts of type	abnormal	GO:0005623	cell	BFO:0000050	part_of	ZFA:0001320	endocardium	ZDB-PUB-130709-36	ZDB-EXP-140306-9	0-0-ZFA:0001315-PATO:0002001-GO:0005623-BFO:0000050-ZFA:0001320	ZP:0014564
```

Compared to:

```
ZDB-FISH-150901-24930	gdf6a<sup>m233/m233</sup>(AB)	ZDB-STAGE-010723-35	Larval:Day 4	ZDB-STAGE-010723-35	Larval:Day 4	ZFA:0009000	cell	BFO:0000050	part_of	ZFA:0000119	retinal inner nuclear layer	PATO:0001997	decreased amount	abnormal							ZDB-PUB-101115-22	ZDB-EXP-041102-1	ZFA:0009000-BFO:0000050-ZFA:0000119-PATO:0001997-0-0-0	ZP:0006134

```

This causes confusion for the labels: both classes GO:0005623 and ZFA:0009000 are labelled 'cell'. Intentional?

**Comment by matentzn** [comment]
These are the definitions for which we now have both a GO:cell and ZFA cell definition (same label): 

ZP:0000998  hair cell anterior macula decreased amount, abnormal	
 ZP:0008499  hair cell anterior macula decreased amount, abnormal	
 ZP:0005992  cell retinal inner nuclear layer decreased amount, abnormal	
 ZP:0006134 	cell retinal inner nuclear layer decreased amount, abnormal	
 ZP:0002061 	cell retina decreased amount, abnormal	
 ZP:0006721 	cell retina decreased amount, abnormal	
 ZP:0010624 	cell parapineal organ mislocalised, abnormal	
 ZP:0012563 	cell parapineal organ mislocalised, abnormal	
 ZP:0006256 	cell lens disorganized, abnormal	
 ZP:0103459 	cell lens disorganized, abnormal	
 ZP:0007542 	cell head apoptotic, abnormal	
 ZP:0011625 	cell head apoptotic, abnormal	
 ZP:0008256  cell EVL morphology, abnormal	
 ZP:0011825 	cell EVL morphology, abnormal

**Comment by matentzn** [comment]
Yvonne will replace GO:Cell with ZFA:Cell.

**Comment by ybradford** [comment]
these have been changed to ZFA cell. it should be available in the file 1/16
