### ISSUE TITLE
ZFIN raw data has not anticipated use of 'BSPO:0000120' (121) (in left/right side of)

### ISSUE THREAD

**Issue by matentzn** [obophenotype/zebrafish-phenotype-ontology#5]
@matentzn commented on [Mon Sep 10 2018](https://github.com/obophenotype/zebrafish-phenotype-ontology-build/issues/4)

In 'Phenotype of Zebrafish Genes' dataset (https://zfin.org/downloads/phenoGeneCleanData_fish.txt), ZFIN annotates a few genes using BSPO:0000120 (in left side of) and the respective 'in right side of'. Both BSPO identifiers refer to *object properties*, not classes; ZPGen assumes the column contains classes. Question to @ybradford : These are only a handful of records; is it possible that the intention was to use `BSPO:0000000` (left side) or `BSPO:0000007` (right side) instead?

```
/data $ wget https://zfin.org/downloads/phenoGeneCleanData_fish.txt
/data $ grep BSPO:0000120 phenoGeneCleanData_fish.txt 
169650585	ephb4b	ZDB-GENE-990415-65	BSPO:0000120	in_left_side_of	BFO:0000050	part_of	ZFA:0000121	lateral plate mesoderm	PATO:0000462	absent	abnormal							ZDB-FISH-161209-1	TU + MO2-ephb4b	ZDB-STAGE-010723-16	ZDB-STAGE-010723-16	ZDB-GENOX-161209-3	ZDB-PUB-160612-7	ZDB-FIG-160818-15
169657538	klf8	ZDB-GENE-070424-152	BSPO:0000120	in_left_side_of	BFO:0000050	part_of	ZFA:0000101	diencephalon	PATO:0000462	absent	abnormal	ZDB-FISH-180605-11	AB + MO1-klf8	ZDB-STAGE-010723-16	ZDB-STAGE-010723-16	ZDB-GENOX-180605-12	ZDB-PUB-170720-15	ZDB-FIG-180118-30
169657540	klf8	ZDB-GENE-070424-152	BSPO:0000120	in_left_side_of	BFO:0000050	part_of	ZFA:0000101	diencephalon	PATO:0000462	absent	abnormal	ZDB-FISH-180605-12	AB + MO2-klf8	ZDB-STAGE-010723-16	ZDB-STAGE-010723-16	ZDB-GENOX-180605-13	ZDB-PUB-170720-15	ZDB-FIG-180118-30
169648499	meis3	ZDB-GENE-010406-2	BSPO:0000120	in_left_side_of	BFO:0000050	part_of	ZFA:0001323	mid intestine	PATO:0000462	absent	abnormal	ZDB-FISH-160212-5	AB + MO1-meis3	ZDB-STAGE-010723-9	ZDB-STAGE-010723-9	ZDB-GENOX-160212-9	ZDB-PUB-150912-13	ZDB-FIG-160212-9
169648501	meis3	ZDB-GENE-010406-2	BSPO:0000120	in_left_side_of	BFO:0000050	part_of	ZFA:0001076	intestinal bulb	PATO:0000628	mislocalised	abnormal							ZDB-FISH-160212-5	AB + MO1-meis3	ZDB-STAGE-010723-9	ZDB-STAGE-010723-9	ZDB-GENOX-160212-9	ZDB-PUB-150912-13	ZDB-FIG-160212-9
/data $ grep BSPO:0000121 phenoGeneCleanData_fish.txt 
169650586	ephb4b	ZDB-GENE-990415-65	BSPO:0000121	in_right_side_of	BFO:0000050	part_of	ZFA:0000121	lateral plate mesoderm	PATO:0000628	mislocalised	abnormal							ZDB-FISH-161209-1	TU + MO2-ephb4b	ZDB-STAGE-010723-16	ZDB-STAGE-010723-16	ZDB-GENOX-161209-3	ZDB-PUB-160612-7	ZDB-FIG-160818-15
169648503	meis3	ZDB-GENE-010406-2	BSPO:0000121	in_right_side_of	BFO:0000050	part_of	ZFA:0001323	mid intestine	PATO:0000462	absent	abnormal							ZDB-FISH-160212-5	AB + MO1-meis3	ZDB-STAGE-010723-9	ZDB-STAGE-010723-9	ZDB-GENOX-160212-9	ZDB-PUB-150912-13	ZDB-FIG-160212-9
169648502	meis3	ZDB-GENE-010406-2	BSPO:0000121	in_right_side_of	BFO:0000050	part_of	ZFA:0001076	intestinal bulb	PATO:0000628	mislocalisedabnormal							ZDB-FISH-160212-5	AB + MO1-meis3	ZDB-STAGE-010723-9	ZDB-STAGE-010723-9	ZDB-GENOX-160212-9	ZDB-PUB-150912-13	ZDB-FIG-160212-9
/data $ 
```

---

@matentzn commented on [Thu Sep 20 2018](https://github.com/obophenotype/zebrafish-phenotype-ontology-build/issues/4#issuecomment-423229654)

In my latest run, I found a few more of those:

<http://purl.obolibrary.org/obo/BSPO_0000120> (in left side of)
<http://purl.obolibrary.org/obo/BSPO_0000098> (dorsal to)
<http://purl.obolibrary.org/obo/BSPO_0000099> (posterior to)
<http://purl.obolibrary.org/obo/BSPO_0000121> (in right side of)
<http://purl.obolibrary.org/obo/BSPO_0000096> (anterior to)

Can someone at ZFIN check whether, given, https://zfin.org/downloads/phenoGeneCleanData_fish.txt, Column D, the following replacements can be made to the annotations:

BSPO:0000120 (in left side of) -> [BSPO:0000000](https://www.ebi.ac.uk/ols/ontologies/bspo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBSPO_0000000) (left side)
BSPO:0000098 (dorsal to) -> [BSPO: 0000063](https://www.ebi.ac.uk/ols/ontologies/bspo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBSPO_0000063) (dorsal side)
BSPO:0000099 (posterior to) -> [BSPO:0000056](https://www.ebi.ac.uk/ols/ontologies/bspo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBSPO_0000056) (posterior side)
BSPO:0000121 (in right side of) -> [BSPO:0000007](https://www.ebi.ac.uk/ols/ontologies/bspo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBSPO_0000007) (right side)
BSPO:0000096 (anterior to) -> [BSPO:0000055](https://www.ebi.ac.uk/ols/ontologies/bspo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FBSPO_0000055) (anterior side)

**Comment by ybradford** [comment]
I can look over these

**Comment by matentzn** [comment]
See [here](https://github.com/obophenotype/zebrafish-phenotype-ontology/blob/master/src/curation/bspo.txt_zp_zfin_phenotype_fish.tsv) for all 14 annotations with reference to those. 

There are [no references](https://github.com/obophenotype/zebrafish-phenotype-ontology/blob/master/src/curation/bspo.txt_zp_zfin_phenoGeneCleanData_fish.tsv) in the gene annotations.

**Comment by ybradford** [comment]
These should all be fixed in the file available 1/15
