### ISSUE TITLE
ZP:0019257 - "obsolete mitotic chromosome decondensation premature, abnormal"

### ISSUE THREAD

**Issue by matentzn** [obophenotype/zebrafish-phenotype-ontology#53]
@ybradford ZFIN is using the following obsolete GO term:

```
ZDB-FISH-151223-12	esco2<sup>hi2865Tg/hi2865Tg</sup>	ZDB-STAGE-010723-10	Pharyngula:Prim-5	ZDB-STAGE-010723-10	Pharyngula:Prim-5					GO:0007083	obsolete mitotic chromosome decondensation	PATO:0000694	premature	abnormal							ZDB-PUB-150606-7	ZDB-EXP-041102-1	0-0-GO:0007083-PATO:0000694-abnormal-0-0-0	
```

**Comment by ybradford** [comment]
@matentzn just fixed this. should hit our files tonight.

**Comment by ybradford** [comment]
Closing for now. If still and issue, re-open.

**Comment by matentzn** [comment]
As of today, this is still an issue

**Comment by ybradford** [comment]
@matentzn Where are you picking up the file from? In my downloads files this term is not present. https://zfin.org/downloads/phenotype_fish.txt

**Comment by matentzn** [comment]
Ok I will try it again! That is where i get them from!

**Comment by matentzn** [comment]
Now fixed, thanks @ybradford
