### ISSUE TITLE
Retiring the NBO Phenotype branch

### ISSUE THREAD

**Issue by DitchingIt** [obophenotype/zebrafish-phenotype-ontology#57]
The NBO is planning to retire its Phenotype branch (no date set yet). We are not aware that ZP has been using any terms from this branch, but you may want to double-check. I recommend tagging @matentzn in follow-up comments, not least if you need a technical discussion.

**Comment by ybradford** [comment]
ZP does not use NBO. This is not an issue for us.

**Comment by matentzn** [comment]
Thanks @ybradford for confirmation;)
