### ISSUE TITLE
Terms that existed once but no longer exist should be obsoleted instead of removed

### ISSUE THREAD

**Issue by matentzn** [obophenotype/zebrafish-phenotype-ontology#6]
@matentzn commented on [Tue Sep 25 2018](https://github.com/obophenotype/zebrafish-phenotype-ontology-build/issues/10)

For example, 'abnormally abnormal angiogenic sprout' (ZP_0003681) in the last main [build](http://compbio.charite.de/hudson/job/zp-owl/lastSuccessfulBuild/artifact/zp.owl) refers to the quality 'abnormal' (PATO:0000460). In the current ZFIN metadata (neither [gene](https://zfin.org/downloads/phenoGeneCleanData_fish.txt) nor [genome](http://zfin.org/downloads/phenotype_fish.txt) data), there is no single annotation that refers to both the angiogenic sprout (ZFA:0005604) and the PATO quality 'abnormal'.

@drseb is that possible?  

---

@matentzn commented on [Tue Sep 25 2018](https://github.com/obophenotype/zebrafish-phenotype-ontology-build/issues/10#issuecomment-424281974)

In the case that a phenotype that previously existed now changed, we should obsolete the existing class (remove the definition) but still add it to the new ontology.

---

@drseb commented on [Tue Sep 25 2018](https://github.com/obophenotype/zebrafish-phenotype-ontology-build/issues/10#issuecomment-424282863)

Can you help debug? Which gene/genotype/morpholino has previously been associated with that?

---

@matentzn commented on [Tue Sep 25 2018](https://github.com/obophenotype/zebrafish-phenotype-ontology-build/issues/10#issuecomment-424286192)

I looked through the old versions of the old ZFIN raw data. There are many annotations with the sprout, but none that have the abnormal Qualifier in the place of the Quality. I gladly keep looking at this issue, but my expectation is that such changes can and will occur from time to time..

---

@drseb commented on [Tue Sep 25 2018](https://github.com/obophenotype/zebrafish-phenotype-ontology-build/issues/10#issuecomment-424286805)

Yes. Those issues will arise often. Hmm... we need a new strategy. Obsoletion is probably not solving the issue, because what will happen if it is used in a future release? Unobsolete again?

---

@matentzn commented on [Tue Sep 25 2018](https://github.com/obophenotype/zebrafish-phenotype-ontology-build/issues/10#issuecomment-424286935)

That is what I was thinking! Why not :P 

---

@drseb commented on [Tue Sep 25 2018](https://github.com/obophenotype/zebrafish-phenotype-ontology-build/issues/10#issuecomment-424287215)

If you think it is a valid option I am okay with it. Would love to hear from others if that is okay. @balhoff ?

---

@matentzn commented on [Tue Sep 25 2018](https://github.com/obophenotype/zebrafish-phenotype-ontology-build/issues/10#issuecomment-424288588)

I mean, there are three alternatives: 
1. they are removed, and we track the fact that they existed once in a separate file to ensure the same IRI is not used again.
2. they are obsoleted (EQ is removed) and unobsoleted as ZFIN raw data changes
3. they are carried over and from release to release, and simply never change.

Both 2 and 3 are valid, as a phenotypic description does not necessarily become invalid just because it is not used in any of the annotations. Above case is a bit of an exception, because I am trying to push the community to distinguish between modifiers and qualities, and abnormal is not a quality, it is a modifier, and therefore does not belong in the quality slot.  I advocate 2. I dont think 1. is a good option at all, both for administrative and conceptual reasons.

---

@matentzn commented on [Tue Sep 25 2018](https://github.com/obophenotype/zebrafish-phenotype-ontology-build/issues/10#issuecomment-424288889)

@dosumis @cmungall if you have strong opinions here

---

@drseb commented on [Tue Sep 25 2018](https://github.com/obophenotype/zebrafish-phenotype-ontology-build/issues/10#issuecomment-424290228)

At the moment (I have to think about it again later) I vote for 3, as it is the simplest solution. 
But this would require more information about the reason for the class' disappearance in the ZFIN data. Can we get a comment from ZFIN on typical reasons? If they simply replaced it with a more specific annotation, then the previously chosen class is still correct. If it was a clear error in the first place than option 2 would be the better choice. Let's hear what others say ;-)

---

@matentzn commented on [Tue Sep 25 2018](https://github.com/obophenotype/zebrafish-phenotype-ontology-build/issues/10#issuecomment-424298487)

I pinged them on slack. :)

---

@matentzn commented on [Tue Sep 25 2018](https://github.com/obophenotype/zebrafish-phenotype-ontology-build/issues/10#issuecomment-424310111)

I quickly took a look at the diffs:

- Number of phenotypes in the current build (2015): 18,461
- Number of phenotypes in new build (today): 26,197
- Number of phenotypes appearing in both: 17,211
- Number of phenotypes that are only in old, i.e. disappeared [(file list)](https://github.com/obophenotype/zebrafish-phenotype-ontology-build/files/2415040/zp_classes_that_disappeared.txt): 1,250

As an irrelevant side note: I also noticed that 105 labels (from all those phenotypes that appear in both versions of ZP) vary quite significantly (either because labels in GO change, or in PATO, or perhaps in ZFA). 

---

@balhoff commented on [Tue Sep 25 2018](https://github.com/obophenotype/zebrafish-phenotype-ontology-build/issues/10#issuecomment-424411281)

I'm okay with "un-obsoleting" when needed. However I feel like if the expression is satisfiable, it doesn't hurt anything to keep in (option 3). Some others outside of ZFIN are using ZP (for example Rong-Lin).

---

@drseb commented on [Wed Sep 26 2018](https://github.com/obophenotype/zebrafish-phenotype-ontology-build/issues/10#issuecomment-424712927)

@cmungall this is all so long ago... (we were so young back then ;-) ). Do you remember more details from our work? It is not written in the F1000 paper, but looking at the classes that have no direct gene association I assume that we automatically generated more general class expressions. E.g. abnormal length X would imply that we add abnormal X to ZP. (I think we have done this, but I am not sure)

**Comment by cmungall** [comment]
I'm not aware of any such rules for ZP specifically

**Comment by drseb** [comment]
What is happening with all these issues? Why are they moved?
