### ISSUE TITLE
Missing GO terms?

### ISSUE THREAD

**Issue by matentzn** [obophenotype/zebrafish-phenotype-ontology#60]
We have the following 18 missing GO terms needed to construct a total of 44 classes in ZP. Most likely these classes were, at some point in the past, used by ZFIN to describe phenotypes. We need to decide what to do with these.

- http://purl.obolibrary.org/obo/GO_0000784
- http://purl.obolibrary.org/obo/GO_0000790
- http://purl.obolibrary.org/obo/GO_0005720
- http://purl.obolibrary.org/obo/GO_0005913
- http://purl.obolibrary.org/obo/GO_0006975
- http://purl.obolibrary.org/obo/GO_0007050
- http://purl.obolibrary.org/obo/GO_0014024
- http://purl.obolibrary.org/obo/GO_0015696
- http://purl.obolibrary.org/obo/GO_0031081
- http://purl.obolibrary.org/obo/GO_0031572
- http://purl.obolibrary.org/obo/GO_0042493
- http://purl.obolibrary.org/obo/GO_0044117
- http://purl.obolibrary.org/obo/GO_0048739
- http://purl.obolibrary.org/obo/GO_0048747
- http://purl.obolibrary.org/obo/GO_0071156
- http://purl.obolibrary.org/obo/GO_0071850
- http://purl.obolibrary.org/obo/GO_0072358
- http://purl.obolibrary.org/obo/GO_1990126

@ybradford while I am preparing a new release, can you determine what happened with these and if they are still needed by ZFIN? I could just mass obsolete all phenotypes related to these classes, but it seems unfortunate to keep obsoleting so many classes per year.

(a) what happened with these (some don't resolve in GO)

**Comment by ybradford** [comment]
@matentzn I believe some terms were obsoleted by GO and we updated our annotations to use either the new replaced by term or a different term: 
GO_0000784 was replaced by GO:0007050 
GO:0014024 was replaced by GO:0014020 
GO:0015696 was replaced by GO:0072488
GO:0031081 was replaced by GO:0051664
GO:0031572 was replaced by GO:0007095
GO:0042493 was replaced by GO:0009410
GO:0044117 was replaced by GO:0051701

I haven't looked precisely. I'd need PMID to map.

**Comment by matentzn** [comment]
@ybradford FYI, the following GO terms are obsolete, and I had to retire some ZP ids: to be able to run the release:

- GO:0016571
- GO:0016573
- GO:0032991
- GO:0043966
- GO:0043967
- GO:0051568
- GO:0070584
- GO:0080182
- GO:0086024
- GO:0097198
- GO:0097676

I am assuming this issue will be fixed (or is already fixed) on the ZFIN side.
