### ISSUE TITLE
GO deprecated various histone terms

### ISSUE THREAD

**Issue by matentzn** [obophenotype/zebrafish-phenotype-ontology#64]
GO deprecated various histone terms (the one with X ZFIN has already dealt with):

- [X] GO:0010452
- [x] GO:0016570
- [x] GO:0034770
- [x] GO:0035518
- [X] GO:0043970
- [X] GO:0043974
- [x] GO:0043984
- [x] GO:0043985
- [x] GO:0051567
- [x] GO:0070734
- [x] GO:0098532
- [x] GO:1900109
- [x] GO:1905066

histone H2A monoubiquitination
histone H3-K27 acetylation
histone H3-K27 methylation
histone H3-K27 trimethylation
histone H3-K36 methylation
histone H3-K9 acetylation
histone H3-K9 methylation
histone H4-K16 acetylation
histone H4-K20 methylation
histone H4-R3 methylation
histone arginine methylation
histone modification
regulation of canonical Wnt signaling pathway involved in heart development
regulation of histone H3-K9 dimethylation

@ybradford you should replace these in ZFIN - I will deprecate them.

**Comment by ybradford** [comment]
These were all taken care of some time ago. Sorry for the delay in commenting on the issue @matentzn
